In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import os 
path='/content/gdrive/MyDrive/MachineLearning/Ensemble Learning'
os.chdir(path)

In [ ]:
# Importin necessary libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [ ]:
import pickle as pkl

In [ ]:

Xtest=pkl.load(open('/content/gdrive/MyDrive/MachineLearning/SVM/svcXtest.pkl','rb'))
Xtrain=pkl.load(open('/content/gdrive/MyDrive/MachineLearning/SVM/svcXtrain.pkl','rb'))
ytest=pkl.load(open('/content/gdrive/MyDrive/MachineLearning/SVM/svcytest.pkl','rb'))
ytrain=pkl.load(open('/content/gdrive/MyDrive/MachineLearning/SVM/svcytrain.pkl','rb'))
svc=pkl.load(open('/content/gdrive/MyDrive/MachineLearning/SVM/svc.pkl','rb'))

In [ ]:
from sklearn.ensemble import RandomForestClassifier  
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV

In [ ]:
params={'criterion':['gini','entropy'], 'max_depth':[5,7,10], 'max_leaf_nodes':[3,5,8]}
rnd=RandomizedSearchCV(RandomForestClassifier(),params,cv=10)
grd=GridSearchCV(RandomForestClassifier(),params,cv=10)
rnd.fit(Xtrain,ytrain)
grd.fit(Xtrain,ytrain)
print(rnd.best_params_)
print(grd.best_params_)

{'max_leaf_nodes': 8, 'max_depth': 10, 'criterion': 'entropy'}
{'criterion': 'entropy', 'max_depth': 7, 'max_leaf_nodes': 8}


In [ ]:
model=RandomForestClassifier(max_leaf_nodes=8,max_depth=10,criterion='gini',n_estimators=50,class_weight='balanced')
random=model.fit(Xtrain,ytrain)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
randomtest=random.predict(Xtest)
randomtrain=random.predict(Xtrain)
print(confusion_matrix(randomtest,ytest))
print(confusion_matrix(randomtrain,ytrain))

[[1299    5]
 [  43  153]]
[[3079   11]
 [  99  311]]


In [ ]:
print(classification_report(randomtest,ytest))
print(classification_report(randomtrain,ytrain))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1304
           1       0.97      0.78      0.86       196

    accuracy                           0.97      1500
   macro avg       0.97      0.89      0.92      1500
weighted avg       0.97      0.97      0.97      1500

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      3090
           1       0.97      0.76      0.85       410

    accuracy                           0.97      3500
   macro avg       0.97      0.88      0.92      3500
weighted avg       0.97      0.97      0.97      3500



In [ ]:
print(confusion_matrix(svc.predict(Xtrain),ytrain))

[[3176   40]
 [   2  282]]
